=== ihongs/HongsCORE.old/web/WEB-INF/conf/db.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- 基础配置 -->
  <xs:element name="config">
    <xs:complexType>
      <xs:attribute name="link" type="xs:string"/>
      <xs:attribute name="dbClass" type="xs:string"/>
      <xs:attribute name="tableClass" type="xs:string"/>
      <xs:attribute name="tablePrefix" type="xs:string"/>
      <xs:attribute name="tableSuffix" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <!-- 数据库驱动 -->
  <xs:element name="driver">
    <xs:complexType>
      <xs:attribute name="link" type="xs:string"/>
      <xs:attribute name="drv" type="xs:string"/>
      <xs:attribute name="url" type="xs:string"/>
      <xs:attribute name="user" type="xs:string" use="required"/>
      <xs:attribute name="password" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- 数据源配置 -->
  <xs:element name="source">
    <xs:complexType>
      <xs:attribute name="link" type="xs:string"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="user" type="xs:string" use="required"/>
      <xs:attribute name="password" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- 关联表配置 -->
  <xs:element name="assoc">
    <xs:complexType>
      <xs:attribute ref="type" use="required"/>
      <xs:attribute ref="join"/>
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="realName"/>
      <xs:attribute ref="foreignKey" use="required"/>
      <xs:attribute ref="primaryKey"/>
      <!-- 其他限定 -->
      <xs:attribute ref="select"/>
      <xs:attribute ref="where"/>
      <xs:attribute ref="groupBy"/>
      <xs:attribute ref="having"/>
      <xs:attribute ref="orderBy"/>
      <xs:all>
        <!-- 递归关联 -->
        <xs:element ref="assoc" minOccurs="0"/>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <!-- 基础表配置 -->
  <xs:element name="table">
    <xs:complexType>
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="alias"/>
      <xs:attribute ref="class"/>
      <xs:attribute ref="prefix"/>
      <xs:attribute ref="suffix"/>
      <xs:attribute ref="primaryKey"/>
      <xs:all>
        <!-- 关联子表 -->
        <xs:element ref="assoc" minOccurs="0"/>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <!-- 基础表集合 -->
  <xs:element name="tables">
    <xs:complexType>
      <xs:all>
        <xs:element ref="table" maxOccurs="unbounded"/>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <!-- 总配置 -->
  <xs:element name="db">
    <xs:complexType>
      <xs:all>
        <xs:element ref="config" minOccurs="0"/>
        <xs:element ref="driver" minOccurs="0"/>
        <xs:element ref="source" minOccurs="0"/>
        <xs:element ref="tables" minOccurs="0"/>
      </xs:all>
    <xs:complexType>
  </xs:element>

</xs:schema>

=== ihongs/HongsCORE.old/web/WEB-INF/conf/db-cims.xml
<?xml version="1.0" encoding="UTF-8"?>

<db xmlns="http://hongs-core"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://hongs-core db.xsd">
    <driver drv="com.mysql.jdbc.Driver"
            url="jdbc:mysql://localhost:3306/hongs_core?useUnicode=true&amp;characterEncoding=utf8&amp;zeroDateTimeBehavior=convertToNull"
            user="root"
            password="123456"/>
    <source name="jdbc/hongs_core"
            user="root"
            password="123456"/>
    <config tablePrefix=""/>
    <tables>
        <table name="ai_item_base_info"
               primaryKey="id">
            <assoc type="HAS_MANY"
                   name="ai_item_attr_info"
                   foreignKey="item_id"
                   primaryKey="item_id"/>
            <assoc type="HAS_MANY"
                   name="ai_item_asoc"
                   foreignKey="item1_id">
                <assoc type="BLS_TO"
                       name="ai_item_base_info"
                       alais="ai_item2_base_info"
                       foreignKey="item2_id"/>
            </assoc>
        </table>
        <table name="ai_item_attr_info"
               primaryKey="id">
        </table>
        <table name="ai_item_asoc"/>
    </tables>
</db>

=== ihongs/HongsCORE.old/web/WEB-INF/conf/db-hctm.xml
<?xml version="1.0" encoding="UTF-8"?>

<db xmlns="http://hongs-core"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://hongs-core db.xsd">
    <config link="default"/>
    <driver link="default"/>
    <source link="default"/>
    <tables>
        <table name="a_hctm_container"
               primaryKey="id">
        </table>
        <table name="a_hctm_code"
               primaryKey="id">
            <assoc type="BLS_TO"
                   name="a_hctm_container"
                   foreignKey="container_id"/>
            <assoc type="HAS_MANY"
                   name="a_hctm_code_rule"
                   foreignKey="code_id">
                <assoc type="BLS_TO"
                       name="a_hctm_rule"
                       foreignKey="rule_id"/>
            </assoc>
        </table>
        <table name="a_hctm_rule"
               primaryKey="id">
            <assoc type="BLS_TO"
                   name="a_hctm_container"
                   foreignKey="container_id"/>
            <assoc type="HAS_MANY"
                   name="a_hctm_rule_item"
                   foreignKey="rule_id">
                <assoc type="BLS_TO"
                       name="a_hctm_var"
                       foreignKey="var_id"/>
            </assoc>
        </table>
        <table name="a_hctm_var"
               primaryKey="id">
            <assoc type="BLS_TO"
                   name="a_hctm_container"
                   foreignKey="container_id"/>
        </table>
        <table name="b_hctm_container"></table>
    </tables>
</db>
