=== ihongs/HongsCORE.old/web/WEB-INF/conf/db.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- 基础配置 -->
  <xs:element name="config">
    <xs:complexType>
      <xs:attribute name="link" type="xs:string"/>
      <xs:attribute name="dbClass" type="xs:string"/>
      <xs:attribute name="tableClass" type="xs:string"/>
      <xs:attribute name="tablePrefix" type="xs:string"/>
      <xs:attribute name="tableSuffix" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <!-- 数据库驱动 -->
  <xs:element name="driver">
    <xs:complexType>
      <xs:attribute name="link" type="xs:string"/>
      <xs:attribute name="drv" type="xs:string"/>
      <xs:attribute name="url" type="xs:string"/>
      <xs:attribute name="user" type="xs:string" use="required"/>
      <xs:attribute name="password" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- 数据源配置 -->
  <xs:element name="source">
    <xs:complexType>
      <xs:attribute name="link" type="xs:string"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="user" type="xs:string" use="required"/>
      <xs:attribute name="password" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- 关联表配置 -->
  <xs:element name="assoc">
    <xs:complexType>
      <xs:attribute ref="type" use="required"/>
      <xs:attribute ref="join"/>
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="realName"/>
      <xs:attribute ref="foreignKey" use="required"/>
      <xs:attribute ref="primaryKey"/>
      <!-- 其他限定 -->
      <xs:attribute ref="select"/>
      <xs:attribute ref="where"/>
      <xs:attribute ref="groupBy"/>
      <xs:attribute ref="having"/>
      <xs:attribute ref="orderBy"/>
      <xs:all>
        <!-- 递归关联 -->
        <xs:element ref="assoc" minOccurs="0"/>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <!-- 基础表配置 -->
  <xs:element name="table">
    <xs:complexType>
      <xs:attribute ref="name" use="required"/>
      <xs:attribute ref="alias"/>
      <xs:attribute ref="class"/>
      <xs:attribute ref="prefix"/>
      <xs:attribute ref="suffix"/>
      <xs:attribute ref="primaryKey"/>
      <xs:all>
        <!-- 关联子表 -->
        <xs:element ref="assoc" minOccurs="0"/>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <!-- 基础表集合 -->
  <xs:element name="tables">
    <xs:complexType>
      <xs:all>
        <xs:element ref="table" maxOccurs="unbounded"/>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <!-- 总配置 -->
  <xs:element name="db">
    <xs:complexType>
      <xs:all>
        <xs:element ref="config" minOccurs="0"/>
        <xs:element ref="driver" minOccurs="0"/>
        <xs:element ref="source" minOccurs="0"/>
        <xs:element ref="tables" minOccurs="0"/>
      </xs:all>
    <xs:complexType>
  </xs:element>

</xs:schema>

=== ihongs/HongsCORE.old/web/WEB-INF/etc/search.db.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<db xmlns="http://hongs-core"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://hongs-core db.xsd">
    <source link="default"/>
    <origin link="default"/>
    <tables>
        <!-- 索引文章 -->
        <table name="article"
               tableName="a_search_article"
               primaryKey="id">
            <assoc type="HAS_MANY"
                   name="article_keyword"
                   foreignKey="article_id"/>
            <assoc type="HAS_MANY"
                   name="article_subject"
                   foreignKey="article_id"/>
            <assoc type="HAS_MANY"
                   name="article_related"
                   foreignKey="article_id"/>
        </table>
        <!-- 关键字词 -->
        <table name="keyword"
               tableName="a_search_keyword"
               primaryKey="id">
        </table>
        <!-- 主题分类 -->
        <table name="subject"
               tableName="a_search_subject"
               primaryKey="id">
        </table>
        <!-- 文章的关键字词 -->
        <table name="article_keyword"
               tableName="a_search_article_keyword">
        </table>
        <!-- 文章的主题分类 -->
        <table name="article_subject"
               tableName="a_search_article_subject">
        </table>
        <!-- 文章的关联属性 -->
        <table name="article_related"
               tableName="a_search_article_related">
        </table>
    </tables>
</db>

=== ihongs/HongsCORE.old/web/WEB-INF/conf/db-hcrm.xml
<?xml version="1.0" encoding="UTF-8"?>

<db xmlns="http://hongs-core"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://hongs-core db.xsd">
    <config link="default"/>
    <driver link="default"/>
    <source link="default"/>
    <tables>
        <table name="ar_datasrc_base_info"
               primaryKey="id">
            <assoc type="HAS_MANY"
                   name="ar_datasrc_conf_info"
                   foreignKey="datasrc_id"/>
        </table>
        <table name="ar_dataset_base_info"
               primaryKey="id">
            <assoc type="BLS_TO"
                   name="ar_datasrc_base_info"
                   foreignKey="datasrc_id"/>
            <assoc type="HAS_MANY"
                   name="ar_dataset_conf_info"
                   foreignKey="dataset_id"/>
            <assoc type="HAS_MANY"
                   name="ar_dataset_cols_info"
                   foreignKey="dataset_id"/>
            <assoc type="HAS_MANY"
                   name="ar_dataset_load_log"
                   foreignKey="dataset_id"/>
        </table>
        <table name="ar_datasrc_conf_info"
               primaryKey="id"/>
        <table name="ar_dataset_conf_info"
               primaryKey="id"/>
        <table name="ar_dataset_cols_info"
               primaryKey="id"/>
        <table name="ar_dataset_load_log"
               primaryKey="id"/>
    </tables>
</db>

=== ihongs/HongsCORE.old/web/WEB-INF/conf/db-hcum.xml
<?xml version="1.0" encoding="UTF-8"?>

<db xmlns="http://hongs-core"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://hongs-core db.xsd">
    <source link="default"/>
    <driver link="default"/>
    <tables>
        <table name="a_hcum_user"
               primaryKey="id">
            <assoc type="HAS_MANY"
                   name="a_hcum_user_group"
                   foreignKey="user_id"/>
            <assoc type="HAS_MANY"
                   name="a_hcum_user_dept"
                   foreignKey="user_id">
                <assoc type="BLS_TO"
                       name="a_hcum_dept"
                       foreignKey="dept_id"/>
            </assoc>
        </table>
        <table name="a_hcum_dept"
               primaryKey="id">
            <assoc type="HAS_MANY"
                   name="a_hcum_dept_group"
                   foreignKey="dept_id"/>
        </table>
        <table name="a_hcum_user_dept"/>
        <table name="a_hcum_user_group"/>
        <table name="a_hcum_dept_group"/>
    </tables>
</db>

=== ihongs/HongsCORE.old/web/WEB-INF/conf/db.hcim.xml
<?xml version="1.0" encoding="UTF-8"?>

<db xmlns="http://hongs-core"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://hongs-core db.xsd">
    <source link="default"/>
    <origin link="default"/>
    <tables>
        <table name="a_hcim_model"
               primaryKey="id">
            <assoc type="BLS_TO"
                   name="a_hcim_module"
                   foreignKey="moduel_id"/>
            <assoc type="HAS_MANY"
                   name="a_hcim_model_cols"
                   foreignKey="model_id">
                <assoc type="BLS_TO"
                       name="a_hcim_ctype"
                       foreignKey="ctype_id"/>
            </assoc>
            <assoc type="HAS_MANY"
                   name="a_hcim_model_rels"
                   foreignKey="model_id">
                <assoc type="BLS_TO"
                       name="a_hcim_model"
                       foreignKey="assoc_id"/>
            </assoc>
            <assoc type="HAS_MANY"
                   name="a_hcim_model_uniq"
                   foreignKey="model_id">
                <assoc type="HAS_MANY"
                       name="a_hcim_model_uniq_cols"
                       foreignKey="uniq_id">
                    <assoc type="BLS_TO"
                           name="uniq_cols"
                           tableName="a_hcim_model_cols"
                           foreignKey="cols_id"/>
                </assoc>
                <assoc type="HAS_MANY"
                       name="a_hcim_model_uniq_rels"
                       foreignKey="uniq_id">
                    <assoc type="BLS_TO"
                           name="uniq_rels"
                           tableName="a_hcim_model_rels"
                           foreignKey="rels_id"/>
                </assoc>
            </assoc>
        </table>
        <table name="a_hcim_module"
               primaryKey="id"/>
        <table name="a_hcum_ctype"
               primaryKey="id"/>
        <table name="a_hcim_model_cols"
               primaryKey="id"/>
        <table name="a_hcim_model_rels"
               primaryKey="id"/>
        <table name="a_hcim_model_uniq"
               primaryKey="id"/>
        <table name="a_hcim_model_uniq_cols"/>
        <table name="a_hcim_model_uniq_rels"/>
    </tables>
</db>

=== ihongs/HongsCORE.old/web/WEB-INF/etc/demo.db.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<db xmlns="http://hongs-core"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://hongs-core db.xsd">
    <source link="default"/>
    <origin link="default"/>
    <tables>
        <table name="demo1"
               tableName="a_demo_1"
               primaryKey="id">
            <assoc type="HAS_MANY"
                   name="demo2s"
                   tableName="demo2"
                   foreignKey="demo1_id"/>
            <assoc type="HAS_ONE"
                   name="demo5"
                   tableName="demo5"
                   foreignKey="demo1_id"/>
        </table>
        <!-- 多对一 -->
        <table name="demo2"
               tableName="a_demo_2"
               primaryKey="id">
            <assoc type="BLS_TO"
                   name="demo1"
                   tableName="demo1"
                   foreignKey="demo1_id"/>
        </table>
        <!-- 多对多 -->
        <table name="demo4"
               tableName="a_demo_4"
               primaryKey="id">
            <assoc type="HAS_MANY"
                   name="demo2s"
                   tableName="demo3"
                   foreignKey="demo4_id"/>
                <assoc type="BLS_TO"
                       name="demo2"
                       tableName="demo2"
                       foreignKey="demo2_id"/>
        </table>
        <table name="demo5"
               tableName="a_demo_5"
               primaryKey="id">
            <assoc type="BLS_TO"
                   name="demo1"
                   tableName="demo1"
                   foreignKey="demo1_id"/>
        </table>
        <table name="a_demo_3"/>
    </tables>
</db>

=== ihongs/HongsCORE.old/web/WEB-INF/conf/db-adms.xml
<?xml version="1.0" encoding="UTF-8"?>

<db xmlns="http://hongs-core"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://hongs-core db.xsd">
    <source link="default"/>
    <driver link="default"/>
    <tables>
        <!-- 广告 -->
        <table name="aa_ad_base_info"
               primaryKey="id">
            <assoc type="HAS_MANY"
                   name="aa_ad_place_rel"
                   foreignKey="ad_id">
                <assoc type="BLS_TO"
                       join="LEFT"
                       name="aa_place_base_info"
                       foreignKey="place_id"/>
            </assoc>
            <assoc type="HAS_MANY"
                   name="aa_ad_stuff_rel"
                   foreignKey="ad_id">
                <assoc type="BLS_TO"
                       join="LEFT"
                       name="aa_stuff_base_info"
                       foreignKey="stuff_id"/>
            </assoc>
        </table>
        <table name="aa_ad_time_info"
               primaryKey="id">
            <assoc type="BLS_TO"
                   name="aa_ad_base_info"/>
        </table>
        <!-- 广告位 -->
        <table name="aa_place_base_info"
               primaryKey="id">
            <assoc type="BLS_TO" join="LEFT" name="aa_ad_base_info" foreignKey="id">
                
            </assoc>
            <assoc type="HAS_MANY"
                   name="aa_place_style_rel"
                   foreignKey="place_id">
                <assoc type="BLS_TO"
                       name="aa_style_base_info"
                       foreignKey="style_id"/>
            </assoc>
        </table>
        <!-- 素材 -->
        <table name="aa_stuff_base_info"
               primaryKey="id"/>
        <!-- 展现形式 -->
        <table name="aa_style_base_info"
               primaryKey="id"/>
        <!-- 关联表 -->
        <table name="aa_ad_place_rel"/>
        <table name="aa_ad_stuff_rel"/>
        <table name="aa_place_style_rel"/>
    </tables>
</db>

=== ihongs/HongsCORE.old/web/WEB-INF/conf/db-crms.xml
<?xml version="1.0" encoding="UTF-8"?>

<db xmlns="http://hongs-core"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://hongs-core db.xsd">
    <config link="default"/>
    <driver link="default"/>
    <source link="default"/>
    <tables>
        <table name="a_ad_base_info"
               primaryKey="ad_id">
            <assoc type="BLS_TO"
                   name="a_ad_order_base_info"
                   foreignKey="order_id"/>
            <assoc type="BLS_TO"
                   name="a_ad_owner_base_info"
                   foreignKey="owner_id"/>
            <assoc type="BLS_TO"
                   name="a_ad_style_base_info"
                   foreignKey="style_id"/>
            <assoc type="HAS_MANY"
                   name="a_ad_stuff_asoc"
                   foreignKey="ad_id"/>
            <assoc type="HAS_MANY"
                   name="a_ad_place_asoc"
                   foreignKey="ad_id"/>
            <assoc type="HAS_MANY"
                   name="a_ad_time_info"
                   foreignKey="ad_id"/>
        </table>
        <table name="a_ad_order_base_info"
               primaryKey="order_id">
            <assoc type="BLS_TO"
                   name="a_ad_owner_base_info"
                   foreignKey="owner_id"/>
        </table>
        <table name="a_ad_owner_base_info"
               primaryKey="owner_id">
        </table>
        <table name="a_ad_stuff_base_info"
               primaryKey="stuff_id">
            <assoc type="BLS_TO"
                   name="a_ad_owner_base_info"
                   foreignKey="owner_id"/>
        </table>
        <table name="a_ad_place_base_info"
               primaryKey="place_id">
            <assoc type="BLS_TO"
                   name="a_ad_class_base_info"
                   foreignKey="class_id"/>
        </table>
        <table name="a_ad_class_base_info"
               primaryKey="class_id">
        </table>
        <table name="a_ad_style_base_info"
               primaryKey="style_id">
        </table>
        <table name="a_ad_order_asoc"/>
        <table name="a_ad_stuff_asoc"/>
        <table name="a_ad_place_asoc"/>
        <table name="a_ad_time_info"/>
    </tables>
</db>

=== ihongs/HongsCORE.old/web/WEB-INF/conf/db-cums.xml
<?xml version="1.0" encoding="UTF-8"?>

<db xmlns="http://hongs-core"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://hongs-core db.xsd">
    <source link="default"/>
    <driver link="default"/>
    <tables>
        <table name="au_user_base_info"
               primaryKey="user_id">
            <assoc type="HAS_MANY"
                   name="au_user_dept_asoc"
                   foreignKey="user_id"/>
            <assoc type="HAS_MANY"
                   name="au_user_group_asoc"
                   foreignKey="user_id"/>
        </table>
        <table name="au_dept_base_info"
               primaryKey="dept_id">
            <assoc type="HAS_MANY"
                   name="au_user_dept_asoc"
                   foreignKey="dept_id"/>
            <assoc type="HAS_MANY"
                   name="au_dept_group_asoc"
                   foreignKey="dept_id"/>
        </table>
        <table name="au_user_dept_asoc"/>
        <table name="au_user_group_asoc"/>
        <table name="au_dept_group_asoc"/>
    </tables>
</db>
